### ISSUE TITLE
Wrong variable name references `DOLCE_CUSTOM_TEPLATE_PATH`

### ISSUE THREAD

**Issue by peterbuga** [dangrie158/dolce#12]
Wrong references throughout the code of `DOLCE_CUSTOM_TEPLATE_PATH`, as in missing `M` in `TEPLATE`

Nice job though with everything else 👍

**Comment by dangrie158** [comment]
Thanks, that was a picture-perfect copy&past error :)

Fixed in 1541b98 and released as 2.5.1
