### ISSUE TITLE
Container name instead image name?

### ISSUE THREAD

**Issue by dom6770** [dangrie158/dolce#13]
Whenever dolce sends a notification through telegram it only shows the image name, not the container name:

```
There are changes to the status of your containers. The last changes are (newest first):

Time                    Action      Container
10/12/2023, 12:33:22 AM ❌die postgres:latest
```

"postgres:latest" is the image name, not the container name. This makes it not obvious which container, because I have serveral postgres:latest running.

**Comment by dangrie158** [comment]
Hi, thanks for reporting

coincidentally I just noticed this yesterday too :)

I wanted to add some functionality to customise this identifier anyway so I changed the default behaviour as well. See https://dangrie158.github.io/dolce/master/configuration/#container-identifiers for the new options.

If you just want to use the (new) default container names, just make sure to upgrade to the latest version (at least `dangrie158/dolce:v2.6.0`)

**Comment by dom6770** [comment]
Hey 👋🏻

ah, I see. I just updated to 2.6.1. Unfortunately, it's not working too. Now it's just "undefined". Even when I set the label according to the docu. I disabled my custom templates by removing the volume from the docker-compose file.

In the dolce logs the container name is displayed:

`dolce  | INFO   main     new container event received: <"postgres_umami": die>`

Telegram notification:

```
Hello,

There are changes to the status of your containers. The last changes are (newest first):

Time                    Action    Container
10/12/2023, 7:35:16 PM ❌die undefined


If something new happens, you won't be bothered again with updates until 10/12/2023, 7:35:36 PM.
```

**Comment by dangrie158** [comment]
Hi,
Thanks for checking!
 I was puzzled by this as I check with all possible configurations and it worked. Turn out I forgot to push the changes before building the new version and used the local version for testing 🤦

Sorry about that. v2.6.2 should finally fix the issue.

**Comment by dom6770** [comment]
Relatable! But yeah, it's working now. Thank you 👍 

I've found some other issues with my build, I'll open new issues the next days, maybe we can resolve that too.

Loving dolce so far. Thanks for the work :)

**Comment by dangrie158** [comment]
That’s great.

Sure, I‘m happy if it works for other people and add features if they are missing :)
