### ISSUE TITLE
sort doesn't work

### ISSUE THREAD

**Issue by sabey** [dangrie158/dolce#16]
Hey, sorry I don't really know javascript so I can't investigate too much, but it seems that sort does not work.

I tried both of these but both returned a list sorted by the newest events first:
```
<% it.events.toSorted(it.newest_first).forEach(event => { %>
<% it.events.toReversed(it.newest_first).forEach(event => { %>

restart		container			3/20/2024, 3:24:16 AM
start		containerl			3/20/2024, 3:24:16 AM
die		container			3/20/2024, 3:24:15 AM
stop		container			3/20/2024, 3:24:15 AM
```

**Comment by dangrie158** [comment]
Hi,

looks like the events are already in the order you want. `toReversed()` does not take a comparator function (see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/toReversed) so it always just reverses the order without sorting it first, which, by coincidence, is just the same as `newest_first`.

To not rely on the undocumented behavior that the oldest events are the first in the list, you should probably explicitly sort first and then reverse like so:

`it.events.toSorted(newest_first).toReversed().forEach(…`

**Comment by sabey** [comment]
I tried both `<% it.events.forEach(event => { %>` and `<% it.events.toSorted(it.newest_first).toReversed().forEach(event => { %>` and they seemed to work as intended!

Thanks, and I appreciate the tool you've made!
