### ISSUE TITLE
Upgrading (docker) to versions v2.9.0 and v2.10.0 breaks docker.sock usage

### ISSUE THREAD

**Issue by peterbuga** [dangrie158/dolce#19]
As title says, after upgrading to latest versions unix docker.sock connection throws a not found host error. 

As a fix, I had to move it over to a tcp connection instead.

**Comment by dangrie158** [comment]
Hi,

can you provide the output and the config file you use? I just tested it with unspecified (default) socket and can't reproduce the problem.

**Comment by dangrie158** [comment]
Hi, thanks for the info. 

I was now able to reproduce the problem and push a fix. You can checkout the latest Version (`v2.10.7`)

**Comment by peterbuga** [comment]
hi @dangrie158 
confirmed 👍 working as expected now! thanks for looking into it.
