### ISSUE TITLE
Datetime in notifications

### ISSUE THREAD

**Issue by ndTEC** [dangrie158/dolce#20]
Is it posible to set localtime and not UTC in email notifications?
I mounted /etc/localtime and the datetime in container is in localtime, but the time in notifications is in UTC. Also the date is US format.

**Comment by dangrie158** [comment]
Hi, 

you need to set the `TZ` environment variable for that. I just added a short section about this in the latest documentation: https://dangrie158.github.io/dolce/v2.10.9/configuration/#use-local-timezone-for-eventdates
