### ISSUE TITLE
[Telegram] Prints "undefined" instead of line breaks for restart notification

### ISSUE THREAD

**Issue by enchained** [dangrie158/dolce#22]
My compose:
```
services:
  dolce:
    image: dangrie158/dolce:latest
    container_name: dolce
    restart: unless-stopped
    volumes:
      - /fast/keeper_data/dolce:/var/run/dolce
    environment:
      DOCKER_HOST: docker-proxy:2375
      DOCKER_TRANSPORT: tcp
      TELEGRAM_HTTP_TOKEN: xxx
      TELEGRAM_RECIPIENT_IDS: xxx
      DOLCE_LOCKFILE: /var/run/dolce/lockfile
      TZ: Europe/Helsinki
  docker-proxy:
    image: tecnativa/docker-socket-proxy
    container_name: docker-proxy
    environment:
      INFO: 1
    ports:
      - 127.0.0.1:2375:2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  # dolce-temp-test-container:
  #  image: "ubuntu:latest"
  #  command: "sleep 1; exit 0;"
  #  restart: unless-stopped
```

When I did `docker compose down / up -d` after commenting out the test container, I got this notification on telegram:

<blockquote>
Hello,
It appears that the Dolce service on `servername` restarted after not shutting down normally.
This means it may missed some events, namely it was blind starting 9/9/2024, 3:28:59 PM until 9/9/2024, 3:29:20 PM.

Here is a list of the events that happened in the meantime:
```
Time                    Action    Container
9/9/2024, 3:29:19 PM ✅start undefined9/9/2024, 3:29:19 PM ✅start undefined9/9/2024, 3:29:10 PM ❌die undefined9/9/2024, 3:29:10 PM ⏹️stop undefined9/9/2024, 3:29:10 PM ❌die undefined9/9/2024, 3:29:10 PM ⏹️stop undefined9/9/2024, 3:29:08 PM ❌kill undefined9/9/2024, 3:29:08 PM ❌kill undefined
```
However, this may be incomplete if docker restarted during the downtime.

If you knowingly killed the process you can ignore this message and use docker stop <containername> the next time to avoid this message.
</blockquote>

Looks like there are some issues with the line break character in the telegram notifications? 

For some reason notifications about events did not have the same issue:

<blockquote>
Hello,

There are changes to the status of your containers. The last changes are (newest first):

```
Time                    Action    Container
9/9/2024, 3:25:57 PM ✅start dolce-dolce-temp-test-container-1
9/9/2024, 3:25:56 PM ❌die dolce-dolce-temp-test-container-1
9/9/2024, 3:25:54 PM ✅start dolce-dolce-temp-test-container-1
9/9/2024, 3:25:53 PM ❌die dolce-dolce-temp-test-container-1
9/9/2024, 3:25:52 PM ✅start dolce-dolce-temp-test-container-1
9/9/2024, 3:25:51 PM ❌die dolce-dolce-temp-test-container-1
9/9/2024, 3:25:49 PM ✅start dolce-dolce-temp-test-container-1
9/9/2024, 3:25:48 PM ❌die dolce-dolce-temp-test-container-1
9/9/2024, 3:25:47 PM ✅start dolce
9/9/2024, 3:25:47 PM ✅start docker-proxy
```

If something new happens, you won't be bothered again with updates until 9/9/2024, 3:27:37 PM.
</blockquote>

**Comment by dangrie158** [comment]
Hi,

thank you very much for the report and sorry it took that long.

The container names being `undefined` and the missing `\n` at the end were actually 2 separate issues. I fixed all of them in the latest `v3.0.0` release. Please update your container and feel free to create a new issue if the problem persists or you find something else.
