### ISSUE TITLE
No Notifiers (env var / docs issue)

### ISSUE THREAD

**Issue by sabey** [dangrie158/dolce#24]
Hi, I just realized there's been a few breaking changes in the last two weeks and my notifications have been missing. I turned on debugging to figure out what has been going on and I realized these environment variables are no longer optional and I'm not sure if that is intentional. They seem to be optional in the sense that they must be set even if they're empty like `SMTP_USERNAME: ""` but a notifier won't be created if aren't defined.

For example I don't use authentication for my smtp server so I'd assume not setting these environment variables would be fine as the docs say `No authentication is used if unset`

```
DEBUG   notifier         SmtpNotifier configuration invalid, skipping creation
DEBUG   notifier                SMTP_USERNAME is not set and no default value provided
DEBUG   notifier                SMTP_PASSWORD is not set and no default value provided
```

Apprise Tag also seems to no longer be optional (unless set to `APPRISE_TAG: ""`):
```
DEBUG   notifier         trying to create AppriseNotifier
DEBUG   notifier         AppriseNotifier configuration invalid, skipping creation
DEBUG   notifier                APPRISE_TAG is not set and no default value provided
```

If possible it might be nice to up the log notification level if a notifier fails to be created when one environment variable is set?

Thanks again for your app and time!

**Comment by dangrie158** [comment]
Hi, thanks for the report.
I can confirm your issues, sorry about that.

The first issue you reported is a regression from a recent change to remove dependencies from dolce. I fixed the bug now, so if you check out version `3.0.2` or `latest`/`master` you should be able to create the smtp notifier now without specifying the empty strings.

Your second issue is cased by the SMTP lib I used no longer being supported. This was a pain in the past so I will finally pull the plug and write my own. I'll keep you updated if the new version is released.

**Comment by dangrie158** [comment]
Ok, this was quicker than I expected but I was nerdsniped.

In release 3.1.0 everything should be working again as expected. Let me know if you encounter other problems

**Comment by sabey** [comment]
Everything works great now, thank you. I just have to note that you do have to unset environment variables when they are empty otherwise it will assume that's valid credentials like `SMTP_USERNAME: ""`
